### ISSUE TITLE
Criar formulario eletronico para cadastrar encontristas

### ISSUE THREAD

**Issue by gsantosoliver** [gsantosoliver/EC-45#15]
- [x] Copiar o formulario do encontro de Abril (http://bit.ly/2eVIwme) para a pasta do encontro de Novembro (http://bit.ly/2y7ctsb)
- [x] Enviar previa para coordenadores da equipe de mensagem Joel e Fatima para familiarizacao
- [x] Ajustar campos e validacoes
- [x] Comparar formulario com planilha atualizada da secretaria
- [ ] Testar e validar planilha no back-end -> http://bit.ly/2jqV6im
- [x] Treinar o casal coordenador da mensagem Joel e Fatima

**Comment by gsantosoliver** [comment]
- Expressoes regulares para validacao -> https://docs.google.com/spreadsheets/d/1FrQOYNeqTvTUR_zqZIyTia_YrpTV8jqmI6dSl1DJKmo/edit?usp=drive_web
- Formulario para teste de validacao -> https://docs.google.com/forms/d/12ma0BpDG9TbbLlvKQti7LuuPs8lCqbHk9HxqI5g3248/edit?usp=drive_web
- Formulario criado. Link -> https://goo.gl/forms/TloWShkTYbaYxfSL2
- Planilha de coleta de dados -> https://docs.google.com/spreadsheets/d/1HRV6FJ7Qz7HuRyAMwG5MV7DBzy8_1hVbuMmfV7s3hd8/edit#gid=1124806145

**Comment by gsantosoliver** [comment]
Formulario de teste enviado para Joel da Fatima

**Comment by gsantosoliver** [comment]
Formulario final enviado para Fatima. Ainda nao fiz as formulas - para automacao da planilha final. Sera feita assim que tivermos dados reais.

**Comment by gsantosoliver** [comment]
@araujolma - que tal criar as formulas para planilha de coleta de dados do formulario eletronico? No final a planilha de coleta tera 3 worksheets:
- 'Inicial' - serve apenas para cadastrar a data do encontro para calculo de idades, tempo de casado
- 'Form Responses 1' - dados coletados pelo form eletronico 
- 'cadastro geral dos encontristas' - essa falta criar (aqui que preciso do seu talento) tera os dados submetidos no formulario ja no formato e order requirida pelo worksheet que leva o mesmo nome na planilha https://drive.google.com/open?id=0ByvgJo3RPCzsZV93VWotLWRBbWc, que vamos usar no dia do encontro

  A ideia e que no final e que tanto a entrada de dados como a formatacao seja automatica para que no final so copiamos todos os dados dos encontristas da planilha de captura de dados na planilha em Excel que vamos usar la no dia.

 Planilha de coleta de dados a ser editada e essa aqui -> https://docs.google.com/spreadsheets/d/1HRV6FJ7Qz7HuRyAMwG5MV7DBzy8_1hVbuMmfV7s3hd8/edit#gid=1124806145

O que falta fazer?
- [ ] Linkar a planilha com o formulario de captacao de dados (esse deixa que eu mesmo faco)
- [ ] Criar um novo Worksheet que transforma os dados capturados no exato formato do Worksheet 'cadastro geral dos encontristas' da planilha https://drive.google.com/open?id=0ByvgJo3RPCzsZV93VWotLWRBbWc
 
Vc pode usar essa outra planilha aqui, que foi usada no encontro de Abril, como exemplo: https://drive.google.com/open?id=1yxmqArvY8OL3jeiQJZDadczGVkJttZVS64Bi26Gg12c

Um detalhe: nao podemos mais alterar o form em si pois ele ja foi enviado para a equipe de mensagem fazer o cadastro.

**Comment by gsantosoliver** [comment]
Hey @araujolma - nos vamos receber os primeiros papeis para serem cadastrados provavelmente amanha. A planilha estara pronta para receber e computar os dados?

**Comment by gsantosoliver** [comment]
Hey @araujolma - testei o formulario agora e tem um probleminha - o cadastro que acabei de fazer nao aparece no sheet "cadastro geral dos encontristas" - cheguei a comentar sobre esse problema com vc. Vc pode dar uma olhada? Obrigado.

**Comment by araujolma** [comment]
Muito estranho, "puxei" os comandos pra baixo de novo e deu certo! As fórmulas já estavam lá... não sei explicar isso, mas pelo menos agora funcionou, hehe.

**Comment by gsantosoliver** [comment]
@araujolma - se prepare para que esse problema se repita. E mesmo bem estranho, e como se cada entrada no form automaticamente fizesse pular uma linha nas formulas do worksheet 'cadastro geral dos encontristas'. Se vc conseguir arrumar isso ae vc me avisa, pois tentei la atras e nao consegui...

**Comment by gsantosoliver** [comment]
Ordenei o worksheet 'Form Responses 1' da planilha https://docs.google.com/spreadsheets/d/1HRV6FJ7Qz7HuRyAMwG5MV7DBzy8_1hVbuMmfV7s3hd8/edit#gid=1124806145 pelo nome do cracha do marido pois essa vai ser a ordenacao que vamos usar para a maioria das listas que vamos imprimir

**Comment by gsantosoliver** [comment]
Bom, acho que podemos fechar esse aqui ;)
