### ISSUE TITLE
Etiquetas das bagagens

### ISSUE THREAD

**Issue by vansjc** [gsantosoliver/EC-45#18]
- [x] Verificar a data para a entrega das etiquetas da bagagem
- [x] avaliar confecção/compra de 4 etiquetas para casal 
- [x] orçar os itens  e enviar para coordenação aprovar
- [x] imprimir o nome dos encontristas
- [x] Imprimir mapa para os encontristas
- [x] organizar as etiquetas/mapas para entregas para encontristas

**Comment by gsantosoliver** [comment]
Mapas ja foram recortados, todas etiquetas com laco rosa ja foram confeccionados. Ainda falta 
- [ ] Comprar fita azul
- [ ] Finalizar etiquetas com laco azul para finalizar.

**Comment by gsantosoliver** [comment]
Etiquetas e mapas prontos e entregues a equipe de mensagem
