### ISSUE TITLE
Guloseimas

### ISSUE THREAD

**Issue by vansjc** [gsantosoliver/EC-45#21]
- [x] Solicitar itens da caixa de guloseimas para coordenação secretaria
- [x] Definir embalagem da marmitinha
- [x] Orçar os itens  e enviar para coordenação aprovar (marmitinha e boas vindas)
- [x] Comprar itens
- [x] Montar os kits na reunião da equipe
- [x] Imprimir a capa da marmitinha (arte a ser enviada pelo Lincoln da Paty)

**Comment by gsantosoliver** [comment]
Michele disse na reuniao do dia 15/09 que essa e uma das atividades para se fazer quase no final, proximo ao encontro.

**Comment by gsantosoliver** [comment]
Ja temos a embalagem definida (esta na caixa)
Conteudo das embalagens sugerido:
- Biz
- Bala de maracuja 
- Bala de cafe
- Big big de hortela

Docinho de boas vindas

**Comment by gsantosoliver** [comment]
Je e Ro farao a doacao do conteudo da marmitinha. A montagem sera dia 09/11

**Comment by gsantosoliver** [comment]
Montagem feita dia 09/11 com sucesso ;)
