### ISSUE TITLE
Sacolinhas da Pastoral Familiar

### ISSUE THREAD

**Issue by vansjc** [gsantosoliver/EC-45#24]
- [x] Fazer orçamento dos itens da sacolinhas (bloco de anotações, pacote de lenço de papel e canetas) 
- [x] lenço de papel extra para equipe bem estar
- [x] Enviar para aprovação da coordenação
- [x] fazer a compra e apresentar comprovante.
- [x] pegar terço e "como rezar o terço" para incluir na sacolinhas
- [x] Organizar sacolinhas  e entregar para coordenação

**Comment by gsantosoliver** [comment]
sacolinhas montadas dia 09/11 e entregues aos encontristas :)
