### ISSUE TITLE
DIA - Identificação dos quartos

### ISSUE THREAD

**Issue by vansjc** [gsantosoliver/EC-45#28]
- [x] Providenciar a identificação dos quartos
- [x] Fixar nas portas nas portas

**Comment by araujolma** [comment]
- Já foi definido o padrão de identificação para os quartos? 
- Seria uma lista com os nomes dos "integrantes" dos quartos?
- Como será a distribuição dos integrantes, por sinal? Isso é atribuição nossa?

**Comment by gsantosoliver** [comment]
A classificacao dos encontristas foi nos passado pela coordenacao e sao tratados de forma sigilosa. Os numeros dos quartos foram definidos seguidos esses criterios e estao disponveis na planilha: http://bit.ly/2mkHdnz
