### ISSUE TITLE
Infraestrutura

### ISSUE THREAD

**Issue by gsantosoliver** [gsantosoliver/EC-45#34]
- [x] Definir recursos tecnlogicos
- Impressora
- Modem 4G
- Laptops
- Roteador
- Tinta impressora
- Chip 4G para rotear pelo telefone
- Preparar HD Externo com aplicativos para serem instalados (Office, VMWare Fusion, Tuxera NTFS, drives da impressora etc)
- Criar conta generica no gmail e dar acesso ao Google Drive
- Criar conta guest nos MACs para uso do pessoal da equipe de secretaria

**Comment by gsantosoliver** [comment]
Confirmado que Levi e Joana trabalham com MAC.
Chip Vivo Pre pago comprado - falta habilitar o servico 4G
Flavio e Cibele irao ceder impressora reserva
Solicitei marca e modelo da impressora do Flavio e Cibele para instalacao de drivers

**Comment by gsantosoliver** [comment]
Hey @araujolma - da uma olhada nesse aqui e pode listar o que vc achar que vamos precisar para montar a infra la no dia do encontro na secretaria 

Valeu!

**Comment by araujolma** [comment]
Parece estar certo! Eu acrescentaria talvez os cabos, adaptadores de tomada e filtro de linha (de repente não tem tanta tomada lá...). Podemos levar o filtro e os adaptadores, por sinal.

**Comment by gsantosoliver** [comment]
@araujolma - bem lembrado! Obrigado por ja colocar o filtro e adaptadores na sua lista ;)

**Comment by gsantosoliver** [comment]
@araujolma - por favor instale os drives para as impressoras que vamos usar no dia nos computadores que vcs vao levar:
Impressora oficial - HP Officejet PROD 8600 - https://support.hp.com/us-en/drivers/selfservice/hp-officejet-pro-8600-e-all-in-one-printer-series-n911/4322914/model/4323658
http://www.cla.canon.com/cla/en/support/consumer/printers_multifunction/photo_all_in_one_inkjet_printers/pixma_mg3510#driversAndSoftwareTab

Canon MG3510 - http://www.cla.canon.com/cla/en/support/consumer/printers_multifunction/photo_all_in_one_inkjet_printers/pixma_mg3510#driversAndSoftwareTab

No dia nao teremos banda o suficente para baixar os drivers, ja temos que instalar de antemao

Qualquer duvida e so me dar um toque.
