### ISSUE TITLE
Preparar lista de encontristas para equipe de Refeitorio

### ISSUE THREAD

**Issue by gsantosoliver** [gsantosoliver/EC-45#40]
- [x] Renomear o worksheet existent 'Refeitório-fotos' como 'Refeitorio'.
- [x] Incluir uma coluna para indicar o casal mensageiro (essa informacao estao no worksheet 'cadastro geral dos encontristas', 'Visitado')
- [x] Ordenar a lista por nome do casal mensageiro.

**Comment by gsantosoliver** [comment]
Hey @araujolma - chegou a ver esse aqui? Tem alguma duvida?

**Comment by araujolma** [comment]
Falta fazer a ordenação. Acho que é melhor fazer quando todas as informações forem preenchidas...

**Comment by gsantosoliver** [comment]
Prontinho.
