### ISSUE TITLE
Preparar lista para o momento de perdao

### ISSUE THREAD

**Issue by gsantosoliver** [gsantosoliver/EC-45#43]
@araujolma - Na planilha "Cadastro Geral dos Encontristas" (http://bit.ly/2xPngdY) existe um worksheet chamado 'Perdão' aonde e encontrado os nomes dos encontristas. Os nomes estao na ordem que foram cadastrados. Precisamos preparar a lista em ordem alfabetica (pelo nome do marido) e para ser impressa em fonte grande.

**Comment by gsantosoliver** [comment]
Hey @araujolma - Acho que se a gente ja ordenar a planilha de cadastro, na tab 'Form Responses 1' alfabeticamente pelo nome do marido ja deve resolver isso aqui - o que vc acha?

**Comment by araujolma** [comment]
Imagino que resolva sim!

**Comment by gsantosoliver** [comment]
Resolvido
