### ISSUE TITLE
Criar agenda de reunioes

### ISSUE THREAD

**Issue by gsantosoliver** [gsantosoliver/EC-45#5]
- [x] Criar agenda de reunioes no Google Calendar
- [x] Colocar as datas das reunioes - sugestao - sabado de manha em uma semana, sexta a noite na outra - respeitando o calendario da Pastoral Familiar
- [x]  Marcar com urgencia a data do terco
- [x]  Marcar a data para pedidos de camisetas
- [x]  Marcar a confraternizacao - sugestao: sabado apos o encontro
- [x]  Criar mensagem para compartilhar calendario com a coordenacao
- [x]  Compartilhar a agenda com a coordenacao
- [x] Compartilhar a agenda com a equipe de Secretaria

**Comment by gsantosoliver** [comment]
Agenda criada. @vansjc favor conferir e confirmar.

**Comment by gsantosoliver** [comment]
@vansjc - segue a mensagem para compartilhar a agenda com a coordenacao. Por favor, confira se esta ok

> Queridos Coordenadores do 45 EC, a Paz de Jesus!
> 
>   Segue a agenda de reunicoes da Equipe de Secretaria -> http://bit.ly/2f21afU
>   
>   As datas e locais podem sofrer alteracoes - vamos manter esse arquivo sempre atualizados 
> 
>   Segue o link da agenda em formato eletronico caso prefiram usar seu programa de calendario preferido: https://calendar.google.com/calendar/ical/51o3nfco3q8lgirlgeodcghio8%40group.calendar.google.com/public/basic.ics
> 
> Fiquem com Deus
> Vanessa e Gilson

**Comment by vansjc** [comment]
Mensagem do Whats up para Equipe Secretaria

Olá Equipe abençoada! Paz de Jesus

Estamos muito felizes por estar junto de vocês em mais essa missão que nos foi confiada por Deus. Desejamos que nossos trabalhos sejam cheios  amor e alegria para fortalecer todas as famílias envolvidas em mais esse encontro, para isso contaremos com o grande chefe, o poderosíssimo protetor das famílias, Arcanjo São Miguel.

Nosso primeiro encontro acontecerá nessa 15/09 (sexta-feira) às 18h00 na condominio Grand Splendor - R. Corifeu de Azevedo Marques, 3202 - Jardim das Industrias, São José dos Campos - SP

Esperamos vocês!
Gilson & Vanessa

**Comment by gsantosoliver** [comment]
@vansjc, para treinar:
- [ ] mandar a mensagem para o grupo da coordenacao no WhatsApp
- [ ] ticar a atividade no primeiro comentario https://github.com/gsantosoliver/EC-45/issues/5#issue-257038610
- [ ] Fechar esse issue

**Comment by gsantosoliver** [comment]
Mensagem enviada para a equipe de Secretaria informando sobre a agenda de reunioes

> Queridos, boa noite! A Paz de Jesus!
> 
> Segue a agenda de reuniões da Equipe de Secretaria -> http://bit.ly/2f21afU
> 
> As datas e locais podem sofrer alterações - vamos manter esse arquivo sempre atualizado.
> 
> Segue o link da agenda em formato eletrônico, caso prefiram usar seu programa de calendário preferido: https://calendar.google.com/calendar/ical/51o3nfco3q8lgirlgeodcghio8%40group.calendar.google.com/public/basic.ics
> 
> Fiquem com Deus
> Vanessa e Gilson
